/**
 * Regression guard for the installer icon fix
 * (`.work/features/installer-icon-fix/`): asserts `electron/icon.ico` is a
 * proper multi-resolution ICO. Windows shell icon resolution (Explorer,
 * shortcuts, taskbar) requires the standard size set; a single-resolution
 * `.ico` was the leading cause of the installed app/shortcuts showing the
 * generic Electron icon instead of WorkLookingAgent's own icon.
 *
 * This test parses the file's own `ICONDIR` + `ICONDIRENTRY` records (a
 * small, self-contained parser — no need to reuse
 * `scripts/generate-icon.ts`'s internals) rather than depend on a specific
 * generation tool, so it stays meaningful even if the icon is regenerated by
 * a different method in the future.
 */
import fs from "fs";
import path from "path";
import { describe, expect, it } from "vitest";

const ICON_PATH = path.join(__dirname, "..", "..", "electron", "icon.ico");

interface IconDirEntry {
  width: number;
  height: number;
  bitCount: number;
}

function parseIconDir(buffer: Buffer): IconDirEntry[] {
  const reserved = buffer.readUInt16LE(0);
  const type = buffer.readUInt16LE(2);
  const count = buffer.readUInt16LE(4);
  expect(reserved).toBe(0);
  expect(type).toBe(1);

  const entries: IconDirEntry[] = [];
  for (let i = 0; i < count; i++) {
    const offset = 6 + i * 16;
    const rawWidth = buffer.readUInt8(offset);
    const rawHeight = buffer.readUInt8(offset + 1);
    const bitCount = buffer.readUInt16LE(offset + 6);
    entries.push({
      // A stored byte of 0 for width/height encodes 256 per the ICO spec.
      width: rawWidth === 0 ? 256 : rawWidth,
      height: rawHeight === 0 ? 256 : rawHeight,
      bitCount,
    });
  }
  return entries;
}

describe("electron/icon.ico", () => {
  it("is a multi-resolution ICO with the standard 16/32/48/256 sizes at 32bpp", () => {
    const buffer = fs.readFileSync(ICON_PATH);
    const entries = parseIconDir(buffer);

    expect(entries.length).toBeGreaterThanOrEqual(4);

    const sizePairs = new Set(entries.map((e) => `${e.width}x${e.height}`));
    for (const expectedSize of ["16x16", "32x32", "48x48", "256x256"]) {
      expect(sizePairs.has(expectedSize)).toBe(true);
    }

    for (const entry of entries) {
      expect(entry.bitCount).toBe(32);
    }
  });
});
